supports the new NeoStats API version checks and exports __ModInit and __ModFini

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3175,7 +3175,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int main(void) {
 	if (MAJOR >= 2) {
 		if (MINOR >= 5) {
-			if (REV >= 3) {
+			if (REV >= 5) {
 				exit(0);
 			}
 		}
@@ -3210,8 +3210,8 @@ if test "$ns_version_ok" = "yes"; then
 	echo "$as_me:$LINENO: result: Compatible Version" >&5
 echo "${ECHO_T}Compatible Version" >&6;
 else
-	{ { echo "$as_me:$LINENO: error: This Module requires NeoStats 2.5.3 or Higher" >&5
-echo "$as_me: error: This Module requires NeoStats 2.5.3 or Higher" >&2;}
+	{ { echo "$as_me:$LINENO: error: This Module requires NeoStats 2.5.5 or Higher" >&5
+echo "$as_me: error: This Module requires NeoStats 2.5.5 or Higher" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
