prepare for 1.1 release

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3441,7 +3441,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 int main(void) {
 	if (MAJOR >= 2) {
 		if (MINOR >= 5) {
-			if (REV >= 9) {
+			if (REV >= 13) {
 				exit(0);
 			}
 		}
@@ -3476,8 +3476,8 @@ if test "$ns_version_ok" = "yes"; then
 	echo "$as_me:$LINENO: result: Compatible Version" >&5
 echo "${ECHO_T}Compatible Version" >&6;
 else
-	{ { echo "$as_me:$LINENO: error: This Module requires NeoStats 2.5.9 or Higher" >&5
-echo "$as_me: error: This Module requires NeoStats 2.5.9 or Higher" >&2;}
+	{ { echo "$as_me:$LINENO: error: This Module requires NeoStats 2.5.13 or Higher" >&5
+echo "$as_me: error: This Module requires NeoStats 2.5.13 or Higher" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
